# Generated by Django 5.0.4 on 2024-04-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_hobbygpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vershina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.des')),
            ],
        ),
        migrations.CreateModel(
            name='Vetka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('len', models.IntegerField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.des')),
            ],
        ),
    ]
