# Generated by Django 5.0.4 on 2024-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_des_vershina_vetka'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestGetOptimalRouteChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
