# Generated by Django 5.0.4 on 2024-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_vetka_description_alter_vershina_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('start_point', models.IntegerField(blank=True, null=True)),
                ('end_point', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
