# Generated by Django 5.0.4 on 2024-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='end_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='start_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
