# Generated by Django 5.0.4 on 2024-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_state_end_point_alter_state_start_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMessanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
