# Generated by Django 5.0.4 on 2024-04-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_club_events_alter_club_hobbies_alter_club_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='main.hobby'),
        ),
        migrations.AlterField(
            model_name='events',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='main.skill'),
        ),
        migrations.AlterField(
            model_name='events',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='type_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.typeevent'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type_importance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.typeimportance'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='hobby', to='main.skill'),
        ),
    ]
