# Generated by Django 5.0.4 on 2024-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_events_hobbies_alter_events_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
